"""add_schemes

Revision ID: eb96883aad76
Revises: ae21336dbeee
Create Date: 2026-03-16 17:15:24.732396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb96883aad76'
down_revision: Union[str, Sequence[str], None] = 'ae21336dbeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deposit_type', sa.String(length=20), nullable=False),
    sa.Column('payout_type', sa.String(length=20), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.Column('multiples_of', sa.Integer(), nullable=True),
    sa.Column('lock_in_type', sa.String(length=20), nullable=False),
    sa.Column('lock_in_days', sa.Integer(), nullable=True),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('flat_rate', sa.Integer(), nullable=True),
    sa.Column('loan_available', sa.Boolean(), nullable=False),
    sa.Column('loan_eligible_from', sa.String(length=20), nullable=True),
    sa.Column('loan_eligible_after_days', sa.Integer(), nullable=True),
    sa.Column('loan_max_percentage', sa.Integer(), nullable=True),
    sa.Column('loan_rate_type', sa.String(length=30), nullable=True),
    sa.Column('loan_rate_value', sa.Integer(), nullable=True),
    sa.Column('forced_pre_type', sa.String(length=30), nullable=True),
    sa.Column('forced_pre_charge_percentage', sa.Integer(), nullable=True),
    sa.Column('forced_pre_charge_flat', sa.Integer(), nullable=True),
    sa.Column('forced_pre_percent_on_deposit', sa.Integer(), nullable=True),
    sa.Column('pre_maturity_allowed', sa.Boolean(), nullable=False),
    sa.Column('pre_maturity_type', sa.String(length=30), nullable=True),
    sa.Column('pre_maturity_rate_reduction', sa.Integer(), nullable=True),
    sa.Column('pre_maturity_si_rate', sa.Integer(), nullable=True),
    sa.Column('pre_maturity_percent_on_deposit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scheme_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('point', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenure_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('tenure_label', sa.String(length=50), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('rate_general', sa.Integer(), nullable=True),
    sa.Column('rate_senior', sa.Integer(), nullable=True),
    sa.Column('bonus_months', sa.Integer(), nullable=True),
    sa.Column('fixed_maturity_amount', sa.Integer(), nullable=True),
    sa.Column('base_deposit_amount', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenure_slabs')
    op.drop_table('scheme_criteria')
    op.drop_table('schemes')
    # ### end Alembic commands ###
